apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-05-16T13:13:29Z"
  generation: 1
  labels:
    app: ctse-microservices-3
  name: ctse-microservices-3
  namespace: default
  resourceVersion: "5389"
  uid: a4531291-33bf-413f-b469-da71dd4ddc5c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ctse-microservices-3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ctse-microservices-3
    spec:
      containers:
      - image: raveena69/ctse-assignment-microservices-3:v1
        imagePullPolicy: Always
        name: ctse-assignment-microservices-3
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          - containerPort: 3000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
